### ISSUE TITLE
Not all expected postcodes showing on map

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/explorer#34]
E.g. [this file](https://drive.google.com/file/d/1eYu9fXbGbgXhcgR8XFnMXV_XVd42O-QQ/view?ts=5bcef13a) (google drive link) has 1,120 postcodes (plus more with charity/company numbers which could be used to find a postcode). But the insights tool is only showing postcodes for 975 grants.

Link to open insights file: https://insights.threesixtygiving.org/file/ffad6d43b08b6556ff39a739c0959736

**Comment by morchickit** [comment]
This is still not fixed, correct? :-)

**Comment by drkane** [comment]
@morchickit - should now be working, would be helpful if you could test with a new file.
